const Player_Info = {
    'MTk5Mzk0NDExMQ': {
        20200928: {
            Url: '',
            uID: 1993944111,
            Like: 400,
            Avatar: 'Halloween',
            Banner: 'DaddyCALLing',
            ign: "ᴺᴼᴼᴮ᭄ㄚΛＤㄩ★",
            GID: "12345678",
            GPP: "F",
            Elites: [26, 27, 25],
            BRscores: 2903,
            CSranks: 'd' + 4,
            CSstars: 2,
            CSkdaS: 2.31,
            CSwinS: 60,

            SF_G: 5,
            SF_W: 5,
            SF_K: 5,
            SB_T10R: 5,
            SB_KDR: 5,
            SB_avgLT: 5,
            SB_avgDpM: 5,
            SB_MKnOM: 5,
            SB_HSs: 5,
            SB_HSR: 5,

            DF_G: 5,
            DF_W: 5,
            DF_K: 5,
            DB_T10R: 5,
            DB_KDR: 5,
            DB_avgLT: 5,
            DB_avgDpM: 5,
            DB_MKnOM: 5,
            DB_HSs: 5,
            DB_HSR: 5,

            QF_G: 5,
            QF_W: 5,
            QF_K: 5,
            QB_T3R: 5,
            QB_KDR: 5,
            QB_RVI: 200,
            QB_KCDN: 150,
            QB_avgLT: 5,
            QB_avgDpM: 5,
            QB_MKnOM: 5,
            QB_HSs: 5,
            QB_HSR: 5,

            vehi: {
                Amp: ['A0001', 'A0003'],
                Jip: ['J0001', 'J0004'],
                RD: ['RD0002'],
            },
            pet: {
                kt: ['kt1', 'kt2'],
                fx: ['fx1', 'fx2'],
                fl: ['fl1', 'fl2'],
                wg: ['wg1', 'wg2'],
                rc: ['rc1', 'rc2'],
            },
                                emo: {
                c: ['c4', 'c2'],
                r: ['r27', 'r2'],
                l: ['l7', 'l2'],
            },
            weap: {

            },
            First: 'Yadnesh',
            Middle: '',
            Last: 'Akotkar',
            Address: ['Akot', 'Akot', 444101, 'Akola', 'Vidarbha'],
            BOD: 20060414,
            Social: {
                Facebook: '',
                Twitter: '',
                YouTube: '',
                Instagram: '',
                Discord: '',
            },
            Device: 'Redmi Note',
            DeviceT: 'Smartphone',
        },
        20200115: {
            second: '',
        },
        20200401: {
            third: '',
        },
    },
}